webrtc_node:
  ros__parameters:
    camera_name:
    - "Drive"
    - "Secondary"
    camera_path:
    - "/dev/v4l/by-id/usb-Arducam_Arducam_B0495__USB3_2.3MP__Arducam_20231205_0001-video-index0"
    - "/dev/v4l/by-id/usb-HD_Camera_Manufacturer_USB_2.0_Camera-video-index0"
    web_server: true
    web_server_path: "/home/cprt/gstreamer/webrtc/gstwebrtc-api/dist"
